apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
spec:
  type: NodePort
  selector:
    app: minecraft-server
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30000
